### ISSUE TITLE
Failed to activate the local-settings package

### ISSUE THREAD

**Issue by adambuczynski** [s-shin/local-settings#3]
1. Open new atom window
2. Error appears

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [local-settings](https://github.com/s-shin/local-settings) package, v0.3.1

### Stack Trace

Failed to activate the local-settings package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at Object.module.exports.enable (/Users/Adam/.atom/packages/local-settings/lib/local-settings.coffee:61:43)
    at Object.module.exports.activate (/Users/Adam/.atom/packages/local-settings/lib/local-settings.coffee:46:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.sublime-*",
      "bower_components",
      "tmp",
      "temp",
      "fonts"
    ],
    "disabledPackages": [
      "tabs-to-spaces",
      "highlight-line",
      "highlight-selected",
      "autocomplete-css"
    ]
  },
  "local-settings": {
    "configFileName": ".atomrc",
    "autoEnable": true
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v1.1.6
color-picker, v2.0.7
editorconfig, v1.0.0
local-settings, v0.3.1
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by s-shin** [comment]
Oops, maybe [this change](https://github.com/s-shin/local-settings/commit/5146a2801a3249d3a61b74ea415f5304078b6bff#diff-a81fac8844c8e1a0fae2041a6f4c11abR36) is the reason. I should modify [supported atom version](https://github.com/s-shin/local-settings/blob/master/package.json#L9-L11) above v1.x. :persevere:
I'll fix it soon.
But I also recommend you to update atom since v0.211.0 is already old.

Thank you for reporting!

**Comment by s-shin** [comment]
Now I can get the reported error, so this issue is reopend.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [local-settings](https://github.com/s-shin/local-settings) package, v0.3.3


### Stack Trace

Failed to activate the local-settings package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at Object.module.exports.enable (/Users/shin/.atom/packages/local-settings/lib/local-settings.coffee:61:43)
    at Object.module.exports.activate (/Users/shin/.atom/packages/local-settings/lib/local-settings.coffee:46:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-color-highlight",
      "meltdown",
      "stealth-mode"
    ]
  },
  "local-settings": {
    "autoEnable": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.0.28
autocomplete-paths, v1.0.2
block-travel, v1.0.2
color-picker, v2.0.10
file-icons, v1.5.8
highlight-column, v0.5.0
highlight-selected, v0.10.1
japanese-wrap, v0.2.10
language-apache, v1.3.0
language-haskell, v1.1.8
language-jade, v0.5.1
linter, v1.2.3
linter-coffeelint, v1.0.0
linter-eslint, v2.4.3
linter-jshint, v1.0.5
linter-jsxhint, v0.1.2
linter-perl, v0.6.0
linter-tslint, v0.2.3
local-settings, v0.3.3
minimap, v4.11.2
react, v0.12.5
tag, v0.3.0

# Dev
No dev packages
```
