### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by szabba** [s-shin/local-settings#6]
[Enter steps to reproduce below:]

1. Start Atom up.
2. Observe an error notification.

**Atom Version**: 1.3.2
**System**: "Arch Linux"
**Thrown From**: [local-settings](https://github.com/s-shin/local-settings) package, v0.4.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at Object.module.exports.enable (/home/karol/.atom/packages/local-settings/lib/local-settings.coffee:59:41)
    at /home/karol/.atom/packages/local-settings/lib/local-settings.coffee:45:8
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "keybinding-resolver",
      "ionide-fsi",
      "wrap-guide",
      "linter-elm-make"
    ],
    "destroyEmptyPanes": true,
    "projectHome": "/home/karol/src/",
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".cvn",
      ".DS_Store",
      "._*",
      "Thumbds.db",
      "*.pyc",
      "*.pyo"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "local-settings": {
    "autoEnable": true
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
autocomplete-glsl, v0.2.3
autocomplete-python, v1.2.4
bug-report, v0.7.1
django-templates, v0.5.0
file-icons, v1.6.13
file-watcher, v0.4.0
fold-functions, v0.4.3
go-plus, v3.5.2
go-rename, v0.3.0
language-docker, v1.1.6
language-elm, v1.3.0
language-glsl, v2.0.1
language-haskell, v1.5.1
language-latex, v0.6.1
language-python-django-templates, v0.1.0
language-restructuredtext, v0.11.0
language-rust, v0.4.5
language-scala, v1.1.4
language-scheme, v1.4.0
latex, v0.28.2
linter, v1.11.3
linter-flake8, v1.9.3
linter-govet, v0.1.5
linter-jslint, v10.0.0
linter-scalac, v1.2.0
local-settings, v0.4.0
project-manager, v2.6.5
python-isort, v0.0.7
python-tools, v0.6.7
scala-format, v0.1.8
select-rectangle, v1.0.2
toggle-gutter, v0.2.2

# Dev
No dev packages
```

**Comment by szabba** [comment]
Possibly a duplicate of/related to #3

**Comment by s-shin** [comment]
This might occur when atom is opened without any project directory.

**Comment by szabba** [comment]
That seems to be the case.

**Comment by andrewfrankel** [comment]
This is still happening, any updates?

**Comment by s-shin** [comment]
Sadly, nothing..

The reason of this issue was mentioned above

> This might occur when atom is opened without any project directory.

and it looks to be caused by [around here in the code](https://github.com/s-shin/local-settings/blob/master/lib/local-settings.coffee#L53-L58).

I'll fix this if I have sufficient time, but a pull request is also welcome :)
